local lesson =
{
    title = "Procedural graphics",
    apis = "love.image.newImageData  ImageData:mapPixel  love.graphics.newImage  newCanvas",
    help = "Every texture here is generated by code at load time. Space regenerates the noise.",
}

local gradient, checker, plasma, noise, canvas, seed

local function makeGradient()
    local data = love.image.newImageData(160, 160)
    data:mapPixel(function(x, y)
        return x / 159, y / 159, 1 - x / 159, 1
    end)
    return love.graphics.newImage(data)
end

local function makeChecker()
    local data = love.image.newImageData(160, 160)
    data:mapPixel(function(x, y)
        local on = (math.floor(x / 20) + math.floor(y / 20)) % 2 == 0
        if on then
            return 0.95, 0.85, 0.3, 1
        end
        return 0.15, 0.2, 0.3, 1
    end)
    return love.graphics.newImage(data)
end

local function makePlasma()
    local data = love.image.newImageData(160, 160)
    data:mapPixel(function(x, y)
        local v = math.sin(x / 12) + math.sin(y / 9) + math.sin((x + y) / 14) + math.sin(math.sqrt(x * x + y * y) / 10)
        v = (v + 4) / 8
        return v, 0.3 + 0.4 * math.sin(v * 6), 1 - v, 1
    end)
    return love.graphics.newImage(data)
end

local function makeNoise()
    local data = love.image.newImageData(160, 160)
    data:mapPixel(function(x, y)
        local n = love.math.noise(x / 40 + seed, y / 40 + seed) * 0.8 + love.math.noise(x / 12 + seed, y / 12) * 0.2
        if n < 0.45 then
            return 0.1, 0.25, 0.6 + n * 0.5, 1
        elseif n < 0.5 then
            return 0.9, 0.85, 0.55, 1
        elseif n < 0.7 then
            return 0.2, 0.6 - (n - 0.5), 0.2, 1
        end
        return n, n, n, 1
    end)
    return love.graphics.newImage(data)
end

local function makeCanvas()
    local c = love.graphics.newCanvas(160, 160)
    love.graphics.setCanvas(c)
    love.graphics.clear(0.05, 0.08, 0.14, 1)
    for i = 1, 24 do
        love.graphics.setColor(love.math.random(), love.math.random(), love.math.random(), 0.7)
        love.graphics.circle("fill", love.math.random(0, 160), love.math.random(0, 160), love.math.random(6, 30))
    end
    love.graphics.setColor(1, 1, 1)
    love.graphics.setCanvas()
    return c
end

function lesson.load()
    seed = 0
    gradient, checker, plasma = makeGradient(), makeChecker(), makePlasma()
    noise = makeNoise()
    canvas = makeCanvas()
end

function lesson.keypressed(key)
    if key == "space" then
        seed = love.math.random() * 100
        noise = makeNoise()
        canvas = makeCanvas()
    end
end

function lesson.draw()
    local items =
    {
        {gradient, "mapPixel gradient"}, {checker, "checkerboard"}, {plasma, "plasma"},
        {noise, "love.math.noise terrain"}, {canvas, "drawn into a Canvas"},
    }
    for i, item in ipairs(items) do
        local x = 40 + ((i - 1) % 3) * 250
        local y = 80 + math.floor((i - 1) / 3) * 230
        love.graphics.setColor(1, 1, 1)
        love.graphics.draw(item[1], x, y)
        love.graphics.rectangle("line", x, y, 160, 160)
        love.graphics.setColor(0.84, 0.9, 0.96)
        love.graphics.print(item[2], x, y + 168)
    end

    local scaled = 1 + math.sin(love.timer.getTime() * 2) * 0.15
    love.graphics.setColor(1, 1, 1)
    love.graphics.draw(plasma, 650, 330, love.timer.getTime(), scaled * 0.5, scaled * 0.5, 80, 80)
end

return lesson
