# EmbedResources.cmake
#
# Invoked in script mode by the build:
#   cmake -DOUTPUT=<header> -DINPUTS=<file;file;...> -P EmbedResources.cmake
#
# Generates a C header that exposes every input file as
#   static const unsigned char <symbol>[]; static const unsigned int <symbol>_len;
# where <symbol> is the file name with non-alphanumeric characters replaced by '_'.

if(NOT DEFINED OUTPUT OR NOT DEFINED INPUTS)
    message(FATAL_ERROR "EmbedResources.cmake needs -DOUTPUT=<file> and -DINPUTS=<list>")
endif()

set(content "/* Generated by cmake/EmbedResources.cmake - do not edit. */\n#pragma once\n\n")

foreach(input IN LISTS INPUTS)
    get_filename_component(name "${input}" NAME)
    string(REGEX REPLACE "[^A-Za-z0-9]" "_" symbol "${name}")

    file(READ "${input}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR byte_count "${hex_len} / 2")

    # Turn "AABBCC" into "0xAA,0xBB,0xCC," with a line break every 24 bytes.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){24})" "\\1\n" hex "${hex}")

    string(APPEND content "static const unsigned char ${symbol}[] = {\n${hex}\n0x00};\n")
    string(APPEND content "static const unsigned int ${symbol}_len = ${byte_count}u;\n\n")
endforeach()

file(WRITE "${OUTPUT}.tmp" "${content}")
configure_file("${OUTPUT}.tmp" "${OUTPUT}" COPYONLY)
file(REMOVE "${OUTPUT}.tmp")
